### ISSUE TITLE
Bad times in rtplot when plotting ULTRASPEC drift mode frames

### ISSUE THREAD

**Issue by vikdhillon** [HiPERCAM/hipercam#78] opened 2020-02-24 16:25 UTC
When rtplotting ULTRASPEC data taken in drift mode with first=0, one gets junk times, which all have the value 2000-01-01 00:00:00.000. When using first=1, the times are fine. When using first>1, rtplot crashes with the error shown in the attached photo.

![IMG-20200224-WA0002](https://user-images.githubusercontent.com/12181916/75170536-2afdc480-5722-11ea-903a-ab442cb073a9.jpg)

**Comment by trmrsh** [comment] 2020-02-24 19:54
I have merged a load of fixes from trm-dev into the master branch as I think they are useful. This problem should be fixed. Partly a problem caused by hipercam flagging many valid times as "not OK". Reduce files now have an option 'skipbadt' to skip bad times which should be set = yes for ultracam and ultraspec. Also added a script 'rupdate' to enable updating of old reduce files. I am leaving the issue open to remind me to look in more detail at the drift mode times.

**Comment by vikdhillon** [comment] 2020-02-25 11:01
Hi Tom,

Just tested the new pipeline with a drift mode. The times still seem to be
2001-01-01 etc in rtplot. We tried and failed to find a corresponding
skipbadt option in rtplot - does that need to be added?

Cheers,

Vik.

---
Prof. Vik Dhillon, Dept of Physics & Astronomy, Univ of Sheffield,
Sheffield S3 7RH, UK
+44 114 222 4528; www.vikdhillon.staff.shef.ac.uk
---

**Comment by vikdhillon** [comment] 2020-02-25 11:06
Ah - just noticed that the bad times are only present if you do first=0. If
you do first=500 or whatever, it works fine.
Is that expected behaviour due to the fact that only a fraction of the
frames are displayed in rtplot in drift mode when first=0, so no
lookback times are available in the time calculation?


---
Prof. Vik Dhillon, Dept of Physics & Astronomy, Univ of Sheffield,
Sheffield S3 7RH, UK
+44 114 222 4528; www.vikdhillon.staff.shef.ac.uk
---

**Comment by trmrsh** [comment] 2020-02-25 12:04
yes, with first=0, the bad times in rtplot are expected. It can't generate correct times without the preceding timestamps. The important thing to test is 'reduce'.

**Comment by trmrsh** [comment] 2020-02-25 16:45
Does 'reduce' work now with drift mode data?

**Comment by trmrsh** [comment] 2020-02-27 15:00
I am closing this on the basis that I think (a) reduce works which was the main issue, and the times are
genuinely bad for the first frames of drift mode, (b) one still want rtplot to plot frames even if they are bad. I might add an indicator of whether the time is flagged as bad which does not currently seem to be the case in rtplot.

**Closed by trmrsh** 2020-02-27 15:00 UTC
